classDiagram
  class AdaptiveGaussianNoise {
    mean : float
    std_range : tuple[float, float]
    forward(container: DataContainer) DataContainer
  }
  style AdaptiveGaussianNoise fill:#EEDD88
  class ApplyLUT {
    target_dtype : torch.dtype | None
    forward(container: DataContainer) DataContainer
  }
  style ApplyLUT fill:#EEDD88
  class AttributeNode {
    attributes : ItemsView[str, AttributeTypes]
    add_attribute(key: str, value: AttributeTypes)
    add_attributes()
    clear_attributes() None
    get_attribute(key: str) AttributeTypes
    memory_bytes() int
    remove_attribute(key: str) None
    update_attribute(key: str, value: AttributeTypes) None
    update_attributes()
  }
  style AttributeNode fill:#99DDFF
  class AttributeOps {
    add_attribute(path: str, key: str, value: str | int | float | list | tuple | dict | Unit)
    add_attributes(path: str)
    add_unit(path: str, unit: Unit)
    get_all_attributes(path: str) dict[str, str | int | float | list | tuple | dict | Unit]
    get_attribute(path: str, key: str) str | int | float | list | tuple | dict | Unit
    get_attributes(path: str) tuple[str | int | float | list | tuple | dict | Unit, ...]
    get_unit(path: str) Unit
    remove_attribute(path: str, key: str)
    update_attribute(path: str, key: str, value: str | int | float | list | tuple | dict | Unit)
    update_attributes(path: str)
    update_unit(path: str, unit: Unit)
  }
  style AttributeOps fill:#99DDFF
  class BaseBackend {
    remote_source : bool
    close()* None
    download_file(source_path: str, destination_path: str)* None
    exists(file_path: str)* bool
    get_file_list(extensions: tuple[str, ...] | None, num_files: int | None)* list[str]
    get_file_size(file_path: str)* int
    read_file(file_path: str)* IOPathWrapper
    write_file(data: IOPathWrapper, file_path: str)* None
  }
  style BaseBackend fill:#BBCC33
  class BaseDataset {
    cache_built : bool
    files : list[str]
    parent : 'BaseDataset | None'
    transform : _BaseTransform | None
    build_cache(mode: CacheMode, num_workers: int | None)
    get_transform_chain() _BaseTransform
    load_raw_data(idx: int)* DataContainer
    memory_bytes() int
    print_memory_usage()
    release_cache(gc_collect: bool)
  }
  style BaseDataset fill:#44BB99
  class BaseNode {
    name : str
    type : NodeType
    memory_bytes() int
  }
  style BaseNode fill:#99DDFF
  class BaseOps {
    memory_bytes() int
    print_memory_usage()
  }
  style BaseOps fill:#99DDFF
  class BaseParser {
    supported_extensions : tuple[str, ...]
    parse(data: IOPathWrapper)* DataContainer
  }
  style BaseParser fill:#BBCC33
  class BaseReader {
    backend : BaseBackend
    cache_files : bool
    download_files : bool
    files : list[str]
    manifest_path : str
    num_files : int | None
    parser : type[BaseParser] | None
    reader_cache_dir : str
    remote_source : bool
    download(file_paths: list[str] | None, num_workers: int | None) None
    read_file(file_path: str) DataContainer
  }
  style BaseReader fill:#AAAA00
  class BaseWriter {
    backend : BaseBackend
    process_parallel(reader: BaseReader, file_name_pattern: str, compression: CompressionType, compression_opts: int | None, num_workers: int | None)
    write(container: DataContainer, file_name: str, compression: CompressionType, compression_opts: int | None)*
  }
  style BaseWriter fill:#EE8866
  class CallbackTransform {
    callback : Callable[[DataContainer], _BaseTransform]
    is_random : bool
    extra_repr() str
    forward(container: DataContainer) DataContainer
  }
  style CallbackTransform fill:#EEDD88
  class Compose {
    transforms : Sequence[_BaseTransform]
    forward(container: DataContainer) DataContainer
  }
  style Compose fill:#EEDD88
  class CropFrames {
    height : int
    strategy : Literal['C', 'TL', 'TR', 'BL', 'BR']
    width : int
    forward(container: DataContainer) DataContainer
  }
  style CropFrames fill:#EEDD88
  class DataContainer {
  }
  style DataContainer fill:#99DDFF
  class DataContainerBase {
    nodes : NodeAccessor
  }
  style DataContainerBase fill:#99DDFF
  class DataNode {
    data : Tensor
    memory_bytes() int
  }
  style DataNode fill:#99DDFF
  class DataType {
    name
  }
  style DataType fill:#BBCC33
  class DatasetOps {
    add_dataset(path: str, name: str, data: Tensor | ndarray | None)
    add_datasets(path: str)
    get_all_dataset_names() list[str]
    get_all_dataset_paths() list[str]
    get_dataset(path: str) Tensor
    get_datasets() tuple[Tensor, ...]
    remove_dataset(path: str)
    update_dataset(path: str, data: Tensor | ndarray)
    update_datasets()
  }
  style DatasetOps fill:#99DDFF
  class DeserializationOps {
    deserialize(hdf5_data: BytesIO)
    load_from_hdf5(path: str)
  }
  style DeserializationOps fill:#99DDFF
  class EdevisParser {
    supported_extensions : tuple
    parse(data: IOPathWrapper) DataContainer
  }
  style EdevisParser fill:#BBCC33
  class ExtractAmplitude {
    forward(container: DataContainer) DataContainer
  }
  style ExtractAmplitude fill:#EEDD88
  class ExtractPhase {
    unwrap : bool
    forward(container: DataContainer) DataContainer
  }
  style ExtractPhase fill:#EEDD88
  class GaussianNoise {
    mean : float
    std : float
    forward(container: DataContainer) DataContainer
  }
  style GaussianNoise fill:#EEDD88
  class GroupNode {
  }
  style GroupNode fill:#99DDFF
  class GroupOps {
    add_group(path: str, name: str)
    get_all_groups() list[str]
    remove_group(path: str)
  }
  style GroupOps fill:#99DDFF
  class HDF5Parser {
    supported_extensions : tuple
    parse(data: IOPathWrapper) DataContainer
  }
  style HDF5Parser fill:#BBCC33
  class IOPathWrapper {
    file_obj : BytesIO
    file_path : str
    close()
  }
  style IOPathWrapper fill:#BBCC33
  class IndexedThermoDataset {
    files : list[str]
    load_raw_data(idx: int) DataContainer
  }
  style IndexedThermoDataset fill:#44BB99
  class InteractiveAnalyzer {
    annotation_toggle
    clear_button
    colorbar
    colors : list
    container : str
    current_frame : int
    current_frame_data
    cursor_annotation_box
    cursor_annotation_text
    data_unit
    domain_unit
    domain_values
    fig
    frame_ax
    frame_img
    frame_slider
    profile_ax
    selected_points : list[tuple[int, int]]
    tdata
    clear_points(event)
    on_click(event)
    on_mouse_move(event)
    toggle_annotation(event)
    update_frame(frame_idx: float)
  }
  style InteractiveAnalyzer fill:#99DDFF
  class LocalBackend {
    pattern : str
    remote_source : bool
    close()* None
    download_file(source_path: str, destination_path: str)* None
    exists(file_path: str) bool
    get_file_list(extensions: tuple[str, ...] | None, num_files: int | None) list[str]
    get_file_size(file_path: str) int
    read_file(file_path: str) IOPathWrapper
    write_file(data: IOPathWrapper, file_path: str) None
  }
  style LocalBackend fill:#BBCC33
  class LocalReader {
  }
  style LocalReader fill:#AAAA00
  class LocalWriter {
    write(container: DataContainer, file_name: str, compression: CompressionType, compression_opts: int | None)
  }
  style LocalWriter fill:#EE8866
  class MaxNormalize {
    eps : float
    forward(container: DataContainer) DataContainer
  }
  style MaxNormalize fill:#EEDD88
  class MinMaxNormalize {
    eps : float
    forward(container: DataContainer) DataContainer
  }
  style MinMaxNormalize fill:#EEDD88
  class NodeAccessor {
    items() ItemsView[str, NodeTypes]
    keys() KeysView[str]
    values() ValuesView[NodeTypes]
  }
  style NodeAccessor fill:#99DDFF
  class NodeType {
    name
  }
  style NodeType fill:#99DDFF
  class NonUniformSampling {
    interpolate : Literal['nearest', 'linear', 'averaging']
    n_samples : int
    precision : float
    tau : float | None
    forward(container: DataContainer) DataContainer
  }
  style NonUniformSampling fill:#EEDD88
  class PulsePhaseThermography {
    freq_indices : NoneType, list
    forward(container: DataContainer) DataContainer
  }
  style PulsePhaseThermography fill:#EEDD88
  class RandomFlip {
    p_height : float
    p_width : float
    forward(container: DataContainer) DataContainer
  }
  style RandomFlip fill:#EEDD88
  class RandomThermoTransform {
    is_random : bool
  }
  style RandomThermoTransform fill:#EEDD88
  class RemoveFlash {
    method : Literal['excitation_signal', 'max_temp', 'mean_temp_drop']
    offset : int
    forward(container: DataContainer) DataContainer
  }
  style RemoveFlash fill:#EEDD88
  class RootNode {
  }
  style RootNode fill:#99DDFF
  class S3Backend {
    bucket : str
    prefix : str
    remote_source : bool
    close() None
    download_file(source_path: str, destination_path: str) None
    exists(file_path: str) bool
    get_file_list(extensions: tuple[str, ...] | None, num_files: int | None) list[str]
    get_file_size(file_path: str) int
    read_file(file_path: str) IOPathWrapper
    write_file(data: IOPathWrapper, file_path: str) None
  }
  style S3Backend fill:#BBCC33
  class S3Reader {
  }
  style S3Reader fill:#AAAA00
  class S3Writer {
    write(container: DataContainer, file_name: str, compression: CompressionType, compression_opts: int | None)
  }
  style S3Writer fill:#EE8866
  class SelectFrameRange {
    end : int | None
    start : int | None
    forward(container: DataContainer) DataContainer
  }
  style SelectFrameRange fill:#EEDD88
  class SelectFrames {
    frame_indices : list
    forward(container: DataContainer) DataContainer
  }
  style SelectFrames fill:#EEDD88
  class SerializationOps {
    save_to_hdf5(path: str, compression: CompressionType, compression_opts: int | None)
    serialize_to_hdf5(compression: CompressionType, compression_opts: int | None) BytesIO
  }
  style SerializationOps fill:#99DDFF
  class Settings {
    download_dir : str
    log_level : str
    model_config
    num_workers : int
    ensure_exists(v: str) str
    validate_log_level(v: str) str
    validate_num_workers(v: int) int
  }
  style Settings fill:#77AADD
  class SimulationParser {
    supported_extensions : tuple
    parse(data: IOPathWrapper) DataContainer
  }
  style SimulationParser fill:#BBCC33
  class SubtractFrame {
    frame : int
    forward(container: DataContainer) DataContainer
  }
  style SubtractFrame fill:#EEDD88
  class ThermoContainer {
  }
  style ThermoContainer fill:#99DDFF
  class ThermoDataset {
    files : list[str]
    download(num_workers: int | None) None
    load_raw_data(idx: int) DataContainer
  }
  style ThermoDataset fill:#44BB99
  class ThermoTransform {
    is_random : bool
  }
  style ThermoTransform fill:#EEDD88
  class TqdmCallback {
    callback(bytes_amount: int) None
  }
  style TqdmCallback fill:#BBCC33
  class Unit {
    name : str
    quantity : str
    symbol : str
    to_dict() dict
  }
  style Unit fill:#99DDFF
  class VisualizationOps {
    analyse_interactive()
    show_frame(frame_number: int, option: str, cmap: str)
    show_pixel_profile(pixel_pos_x: int, pixel_pos_y: int)
  }
  style VisualizationOps fill:#99DDFF
  class ZScoreNormalize {
    eps : float
    forward(container: DataContainer) DataContainer
  }
  style ZScoreNormalize fill:#EEDD88
  class _BaseTransform {
    is_random : bool
    extra_repr() str
    forward(container: DataContainer)* DataContainer
  }
  style _BaseTransform fill:#EEDD88
  AttributeOps --|> BaseOps
  BaseOps --|> DataContainerBase
  DataContainer --|> AttributeOps
  DataContainer --|> DatasetOps
  DataContainer --|> GroupOps
  DataContainer --|> DeserializationOps
  DataContainer --|> SerializationOps
  DataContainer --|> VisualizationOps
  DatasetOps --|> BaseOps
  GroupOps --|> BaseOps
  AttributeNode --|> BaseNode
  DataNode --|> AttributeNode
  GroupNode --|> AttributeNode
  RootNode --|> BaseNode
  DeserializationOps --|> AttributeOps
  DeserializationOps --|> DatasetOps
  DeserializationOps --|> GroupOps
  SerializationOps --|> BaseOps
  VisualizationOps --|> AttributeOps
  VisualizationOps --|> DatasetOps
  VisualizationOps --|> GroupOps
  ThermoContainer --|> DataContainer
  IndexedThermoDataset --|> BaseDataset
  ThermoDataset --|> BaseDataset
  LocalBackend --|> BaseBackend
  S3Backend --|> BaseBackend
  EdevisParser --|> BaseParser
  HDF5Parser --|> BaseParser
  SimulationParser --|> BaseParser
  LocalReader --|> BaseReader
  S3Reader --|> BaseReader
  AdaptiveGaussianNoise --|> RandomThermoTransform
  GaussianNoise --|> RandomThermoTransform
  RandomFlip --|> RandomThermoTransform
  RandomThermoTransform --|> _BaseTransform
  ThermoTransform --|> _BaseTransform
  ExtractAmplitude --|> ThermoTransform
  ExtractPhase --|> ThermoTransform
  PulsePhaseThermography --|> ThermoTransform
  MaxNormalize --|> ThermoTransform
  MinMaxNormalize --|> ThermoTransform
  ZScoreNormalize --|> ThermoTransform
  ApplyLUT --|> ThermoTransform
  CropFrames --|> ThermoTransform
  RemoveFlash --|> ThermoTransform
  SubtractFrame --|> ThermoTransform
  NonUniformSampling --|> ThermoTransform
  SelectFrameRange --|> ThermoTransform
  SelectFrames --|> ThermoTransform
  CallbackTransform --|> _BaseTransform
  Compose --|> ThermoTransform
  LocalWriter --|> BaseWriter
  S3Writer --|> BaseWriter
  _BaseTransform --o CallbackTransform : callback
  _BaseTransform --o Compose : transforms
