classDiagram
  class AzureBlobBackend {
    container_name : str
    prefix : str
    remote_source : bool
    scheme : str
    close() None
    download_file(source_path: str, destination_path: str) None
    exists(file_path: str) bool
    get_file_identity(file_path: str) str
    get_file_list() list[str]
    get_file_size(file_path: str) int
    read_file(file_path: str) IOPathWrapper
    write_file(data: IOPathWrapper, file_path: str) None
  }
  style AzureBlobBackend fill:#77AADD
  class AzureBlobClientOptions {
    connection_timeout : int | None
    max_block_size : int | None
    max_single_put_size : int | None
    read_timeout : int | None
  }
  style AzureBlobClientOptions fill:#77AADD
  class BackendClientOptions {
    as_kwargs() dict[str, Any]
  }
  style BackendClientOptions fill:#77AADD
  class BaseBackend {
    remote_source : bool
    scheme : str
    close()* None
    download_file(source_path: str, destination_path: str)* None
    exists(file_path: str)* bool
    get_file_identity(file_path: str)* str
    get_file_list()* list[str]
    get_file_size(file_path: str)* int
    read_file(file_path: str)* IOPathWrapper
    write_file(data: IOPathWrapper, file_path: str)* None
  }
  style BaseBackend fill:#77AADD
  class BaseParser {
    supported_extensions : tuple[str, ...]
    parse(data: IOPathWrapper)* DataContainer
  }
  style BaseParser fill:#77AADD
  class DataType {
    name
  }
  style DataType fill:#77AADD
  class EdevisParser {
    supported_extensions : tuple
    parse(data: IOPathWrapper) DataContainer
  }
  style EdevisParser fill:#77AADD
  class HDF5Parser {
    supported_extensions : tuple
    parse(data: IOPathWrapper) DataContainer
  }
  style HDF5Parser fill:#77AADD
  class IOPathWrapper {
    file_obj : BytesIO
    file_path : str
    close()
  }
  style IOPathWrapper fill:#77AADD
  class LocalBackend {
    pattern : str
    remote_source : bool
    scheme : str
    close()* None
    download_file(source_path: str, destination_path: str)* None
    exists(file_path: str) bool
    get_file_identity(file_path: str) str
    get_file_list() list[str]
    get_file_size(file_path: str) int
    read_file(file_path: str) IOPathWrapper
    write_file(data: IOPathWrapper, file_path: str) None
  }
  style LocalBackend fill:#77AADD
  class S3Backend {
    bucket : str
    prefix : str
    remote_source : bool
    scheme : str
    close() None
    download_file(source_path: str, destination_path: str) None
    exists(file_path: str) bool
    get_file_identity(file_path: str) str
    get_file_list() list[str]
    get_file_size(file_path: str) int
    read_file(file_path: str) IOPathWrapper
    write_file(data: IOPathWrapper, file_path: str) None
  }
  style S3Backend fill:#77AADD
  class S3ClientOptions {
    connect_timeout : int | float | None
    max_pool_connections : int | None
    read_timeout : int | float | None
  }
  style S3ClientOptions fill:#77AADD
  class SimulationParser {
    supported_extensions : tuple
    parse(data: IOPathWrapper) DataContainer
  }
  style SimulationParser fill:#77AADD
  class TqdmCallback {
    callback(bytes_amount: int) None
  }
  style TqdmCallback fill:#77AADD
  AzureBlobBackend --|> BaseBackend
  LocalBackend --|> BaseBackend
  AzureBlobClientOptions --|> BackendClientOptions
  S3ClientOptions --|> BackendClientOptions
  S3Backend --|> BaseBackend
  EdevisParser --|> BaseParser
  HDF5Parser --|> BaseParser
  SimulationParser --|> BaseParser
