classDiagram
  class AdaptiveGaussianNoise {
    mean : float
    std_range : tuple[float, float]
    forward(container: DataContainer) DataContainer
  }
  style AdaptiveGaussianNoise fill:#77AADD
  class ApplyLUT {
    target_dtype : torch.dtype | None
    forward(container: DataContainer) DataContainer
  }
  style ApplyLUT fill:#77AADD
  class CallbackTransform {
    callback : Callable[[DataContainer], _BaseTransform]
    is_random : bool
    extra_repr() str
    forward(container: DataContainer) DataContainer
  }
  style CallbackTransform fill:#77AADD
  class Compose {
    transforms : Sequence[_BaseTransform]
    forward(container: DataContainer) DataContainer
  }
  style Compose fill:#77AADD
  class CropFrames {
    height : int
    strategy : Literal['C', 'TL', 'TR', 'BL', 'BR']
    width : int
    forward(container: DataContainer) DataContainer
  }
  style CropFrames fill:#77AADD
  class GaussianNoise {
    mean : float
    std : float
    forward(container: DataContainer) DataContainer
  }
  style GaussianNoise fill:#77AADD
  class MaxNormalize {
    eps : float
    forward(container: DataContainer) DataContainer
  }
  style MaxNormalize fill:#77AADD
  class MinMaxNormalize {
    eps : float
    forward(container: DataContainer) DataContainer
  }
  style MinMaxNormalize fill:#77AADD
  class NonUniformSampling {
    interpolate : bool
    n_samples : int
    precision : float
    tau : float | None
    forward(container: DataContainer) DataContainer
  }
  style NonUniformSampling fill:#77AADD
  class RandomFlip {
    p_height : float
    p_width : float
    forward(container: DataContainer) DataContainer
  }
  style RandomFlip fill:#77AADD
  class RandomThermoTransform {
    is_random : bool
  }
  style RandomThermoTransform fill:#77AADD
  class RemoveFlash {
    method : Literal['excitation_signal', 'max_temp', 'mean_temp_drop']
    offset : int
    forward(container: DataContainer) DataContainer
  }
  style RemoveFlash fill:#77AADD
  class SelectFrameRange {
    end : int | None
    start : int | None
    forward(container: DataContainer) DataContainer
  }
  style SelectFrameRange fill:#77AADD
  class SelectFrames {
    frame_indices : list
    forward(container: DataContainer) DataContainer
  }
  style SelectFrames fill:#77AADD
  class SubtractFrame {
    frame : int
    forward(container: DataContainer) DataContainer
  }
  style SubtractFrame fill:#77AADD
  class ThermoTransform {
    is_random : bool
  }
  style ThermoTransform fill:#77AADD
  class ZScoreNormalize {
    eps : float
    forward(container: DataContainer) DataContainer
  }
  style ZScoreNormalize fill:#77AADD
  class _BaseTransform {
    is_random : bool
    extra_repr() str
    forward(container: DataContainer)* DataContainer
  }
  style _BaseTransform fill:#77AADD
  AdaptiveGaussianNoise --|> RandomThermoTransform
  GaussianNoise --|> RandomThermoTransform
  RandomFlip --|> RandomThermoTransform
  RandomThermoTransform --|> _BaseTransform
  ThermoTransform --|> _BaseTransform
  MaxNormalize --|> ThermoTransform
  MinMaxNormalize --|> ThermoTransform
  ZScoreNormalize --|> ThermoTransform
  ApplyLUT --|> ThermoTransform
  CropFrames --|> ThermoTransform
  RemoveFlash --|> ThermoTransform
  SubtractFrame --|> ThermoTransform
  NonUniformSampling --|> ThermoTransform
  SelectFrameRange --|> ThermoTransform
  SelectFrames --|> ThermoTransform
  CallbackTransform --|> _BaseTransform
  Compose --|> ThermoTransform
  _BaseTransform --o CallbackTransform : callback
  _BaseTransform --o Compose : transforms
