classDiagram
  class BaseBackend {
    remote_source : bool
    close()* None
    download_file(source_path: str, destination_path: str)* None
    exists(file_path: str)* bool
    get_file_list(extensions: tuple[str, ...] | None, num_files: int | None)* list[str]
    read_file(file_path: str)* IOPathWrapper
    write_file(data: IOPathWrapper, file_path: str)* None
  }
  style BaseBackend fill:#77AADD
  class BaseParser {
    supported_extensions : tuple[str, ...]
    parse(data: IOPathWrapper)* DataContainer
  }
  style BaseParser fill:#77AADD
  class DataType {
    name
  }
  style DataType fill:#77AADD
  class EdevisParser {
    supported_extensions : tuple
    parse(data: IOPathWrapper) DataContainer
  }
  style EdevisParser fill:#77AADD
  class HDF5Parser {
    supported_extensions : tuple
    parse(data: IOPathWrapper) DataContainer
  }
  style HDF5Parser fill:#77AADD
  class IOPathWrapper {
    file_obj : BytesIO
    file_path : str
    close()
  }
  style IOPathWrapper fill:#77AADD
  class LocalBackend {
    pattern : str
    remote_source : bool
    close()* None
    download_file(source_path: str, destination_path: str)* None
    exists(file_path: str) bool
    get_file_list(extensions: tuple[str, ...] | None, num_files: int | None) list[str]
    read_file(file_path: str) IOPathWrapper
    write_file(data: IOPathWrapper, file_path: str) None
  }
  style LocalBackend fill:#77AADD
  class S3Backend {
    bucket : str
    prefix : str
    remote_source : bool
    close() None
    download_file(source_path: str, destination_path: str) None
    exists(file_path: str) bool
    get_file_list(extensions: tuple[str, ...] | None, num_files: int | None) list[str]
    read_file(file_path: str) IOPathWrapper
    write_file(data: IOPathWrapper, file_path: str) None
  }
  style S3Backend fill:#77AADD
  class SimulationParser {
    supported_extensions : tuple
    parse(data: IOPathWrapper) DataContainer
  }
  style SimulationParser fill:#77AADD
  LocalBackend --|> BaseBackend
  S3Backend --|> BaseBackend
  EdevisParser --|> BaseParser
  HDF5Parser --|> BaseParser
  SimulationParser --|> BaseParser
