classDiagram
  class Unit {
    name : str
    quantity : str
    symbol : str
  }
  style Unit fill:#77AADD
  class Units {
    arbitrary
    celsius
    dimensionless
    kelvin
    millisecond
    second
    undefined
    print_available_units()
  }
  style Units fill:#77AADD
  Unit --* Units : dimensionless
  Unit --* Units : arbitrary
  Unit --* Units : undefined
  Unit --* Units : kelvin
  Unit --* Units : celsius
  Unit --* Units : second
  Unit --* Units : millisecond
