classDiagram
  class BaseWriter {
    backend : BaseBackend
    \_\_init\_\_()
    write(container: DataContainer, file_name: str)*
  }
  style BaseWriter fill:#77AADD
  class LocalWriter {
    \_\_init\_\_(destination_folder: str)
    write(container: DataContainer, file_name: str)
  }
  style LocalWriter fill:#77AADD
  class S3Writer {
    \_\_init\_\_(bucket: str, prefix: str, region_name: str | None, profile_name: str | None)
    write(container: DataContainer, file_name: str)
  }
  style S3Writer fill:#77AADD
  LocalWriter --|> BaseWriter
  S3Writer --|> BaseWriter
