classDiagram
  class pythermondt {
  }
  style pythermondt fill:#77AADD
  class __pkginfo__ {
  }
  style __pkginfo__ fill:#77AADD
  class config {
  }
  style config fill:#77AADD
  class data {
  }
  style data fill:#99DDFF
  class datacontainer {
  }
  style datacontainer fill:#99DDFF
  class attribute_ops {
  }
  style attribute_ops fill:#99DDFF
  class base {
  }
  style base fill:#99DDFF
  class core {
  }
  style core fill:#99DDFF
  class dataset_ops {
  }
  style dataset_ops fill:#99DDFF
  class group_ops {
  }
  style group_ops fill:#99DDFF
  class node {
  }
  style node fill:#99DDFF
  class serialization_ops {
  }
  style serialization_ops fill:#99DDFF
  class utils {
  }
  style utils fill:#99DDFF
  class visualization_ops {
  }
  style visualization_ops fill:#99DDFF
  class thermo_container {
  }
  style thermo_container fill:#99DDFF
  class units {
  }
  style units fill:#99DDFF
  class _unit {
  }
  style _unit fill:#99DDFF
  class units {
  }
  style units fill:#99DDFF
  class utils {
  }
  style utils fill:#99DDFF
  class dataset {
  }
  style dataset fill:#44BB99
  class base {
  }
  style base fill:#44BB99
  class indexed_thermo_dataset {
  }
  style indexed_thermo_dataset fill:#44BB99
  class thermo_dataset {
  }
  style thermo_dataset fill:#44BB99
  class utils {
  }
  style utils fill:#44BB99
  class io {
  }
  style io fill:#BBCC33
  class backends {
  }
  style backends fill:#BBCC33
  class base_backend {
  }
  style base_backend fill:#BBCC33
  class local_backend {
  }
  style local_backend fill:#BBCC33
  class s3_backend {
  }
  style s3_backend fill:#BBCC33
  class parsers {
  }
  style parsers fill:#BBCC33
  class base_parser {
  }
  style base_parser fill:#BBCC33
  class hdf5_parser {
  }
  style hdf5_parser fill:#BBCC33
  class simulation_parser {
  }
  style simulation_parser fill:#BBCC33
  class utils {
  }
  style utils fill:#BBCC33
  class readers {
  }
  style readers fill:#AAAA00
  class base_reader {
  }
  style base_reader fill:#AAAA00
  class local_reader {
  }
  style local_reader fill:#AAAA00
  class s3_reader {
  }
  style s3_reader fill:#AAAA00
  class transforms {
  }
  style transforms fill:#EEDD88
  class augmentation {
  }
  style augmentation fill:#EEDD88
  class base {
  }
  style base fill:#EEDD88
  class normalization {
  }
  style normalization fill:#EEDD88
  class preprocessing {
  }
  style preprocessing fill:#EEDD88
  class sampling {
  }
  style sampling fill:#EEDD88
  class utils {
  }
  style utils fill:#EEDD88
  class writers {
  }
  style writers fill:#EE8866
  class base_writer {
  }
  style base_writer fill:#EE8866
  class local_writer {
  }
  style local_writer fill:#EE8866
  class s3_writer {
  }
  style s3_writer fill:#EE8866
  pythermondt --> __pkginfo__
  pythermondt --> config
  pythermondt --> data
  pythermondt --> dataset
  pythermondt --> io
  pythermondt --> readers
  pythermondt --> transforms
  pythermondt --> writers
  data --> datacontainer
  data --> thermo_container
  data --> units
  datacontainer --> core
  datacontainer --> node
  attribute_ops --> base
  attribute_ops --> node
  base --> node
  base --> utils
  core --> attribute_ops
  core --> dataset_ops
  core --> group_ops
  core --> node
  core --> serialization_ops
  core --> utils
  core --> visualization_ops
  dataset_ops --> base
  dataset_ops --> node
  dataset_ops --> utils
  group_ops --> base
  group_ops --> node
  group_ops --> utils
  serialization_ops --> attribute_ops
  serialization_ops --> base
  serialization_ops --> dataset_ops
  serialization_ops --> group_ops
  serialization_ops --> node
  serialization_ops --> utils
  utils --> node
  visualization_ops --> attribute_ops
  visualization_ops --> dataset_ops
  visualization_ops --> group_ops
  thermo_container --> datacontainer
  thermo_container --> units
  units --> units
  units --> _unit
  units --> utils
  units --> _unit
  utils --> _unit
  utils --> units
  dataset --> indexed_thermo_dataset
  dataset --> thermo_dataset
  dataset --> utils
  indexed_thermo_dataset --> base
  thermo_dataset --> base
  utils --> indexed_thermo_dataset
  utils --> thermo_dataset
  io --> backends
  io --> parsers
  io --> utils
  backends --> base_backend
  backends --> local_backend
  backends --> s3_backend
  local_backend --> base_backend
  s3_backend --> base_backend
  parsers --> base_parser
  parsers --> hdf5_parser
  parsers --> simulation_parser
  hdf5_parser --> base_parser
  simulation_parser --> base_parser
  readers --> base_reader
  readers --> local_reader
  readers --> s3_reader
  local_reader --> base_reader
  s3_reader --> base_reader
  transforms --> augmentation
  transforms --> base
  transforms --> normalization
  transforms --> preprocessing
  transforms --> sampling
  transforms --> utils
  augmentation --> base
  normalization --> base
  preprocessing --> base
  sampling --> base
  utils --> base
  writers --> base_writer
  writers --> local_writer
  writers --> s3_writer
  local_writer --> base_writer
  s3_writer --> base_writer
