classDiagram
  class datacontainer {
  }
  style datacontainer fill:#F2994A
  class attribute_ops {
  }
  style attribute_ops fill:#F2994A
  class base {
  }
  style base fill:#F2994A
  class core {
  }
  style core fill:#F2994A
  class dataset_ops {
  }
  style dataset_ops fill:#F2994A
  class group_ops {
  }
  style group_ops fill:#F2994A
  class node {
  }
  style node fill:#F2994A
  class serialization_ops {
  }
  style serialization_ops fill:#F2994A
  class utils {
  }
  style utils fill:#F2994A
  class visualization_ops {
  }
  style visualization_ops fill:#F2994A
  datacontainer --> core
  datacontainer --> node
  attribute_ops --> base
  attribute_ops --> node
  base --> node
  base --> utils
  core --> attribute_ops
  core --> dataset_ops
  core --> group_ops
  core --> node
  core --> serialization_ops
  core --> utils
  core --> visualization_ops
  dataset_ops --> base
  dataset_ops --> node
  dataset_ops --> utils
  group_ops --> base
  group_ops --> node
  group_ops --> utils
  serialization_ops --> attribute_ops
  serialization_ops --> base
  serialization_ops --> dataset_ops
  serialization_ops --> group_ops
  serialization_ops --> node
  serialization_ops --> utils
  utils --> node
  visualization_ops --> attribute_ops
  visualization_ops --> dataset_ops
  visualization_ops --> group_ops
