classDiagram
  class units {
  }
  style units fill:#F2994A
  class _unit {
  }
  style _unit fill:#F2994A
  class units {
  }
  style units fill:#F2994A
  class utils {
  }
  style utils fill:#F2994A
  units --> units
  units --> _unit
  units --> utils
  units --> _unit
  utils --> _unit
  utils --> units
