classDiagram
  class units {
  }
  style units fill:#77AADD
  class units {
  }
  style units fill:#77AADD
  class utils {
  }
  style utils fill:#77AADD
  units --> units
  units --> utils
  utils --> units
