classDiagram
  class io {
  }
  style io fill:#77AADD
  class backends {
  }
  style backends fill:#77AADD
  class base_backend {
  }
  style base_backend fill:#77AADD
  class local_backend {
  }
  style local_backend fill:#77AADD
  class s3_backend {
  }
  style s3_backend fill:#77AADD
  class parsers {
  }
  style parsers fill:#77AADD
  class base_parser {
  }
  style base_parser fill:#77AADD
  class edevis_parser {
  }
  style edevis_parser fill:#77AADD
  class hdf5_parser {
  }
  style hdf5_parser fill:#77AADD
  class simulation_parser {
  }
  style simulation_parser fill:#77AADD
  class utils {
  }
  style utils fill:#77AADD
  io --> backends
  io --> parsers
  io --> utils
  backends --> base_backend
  backends --> local_backend
  backends --> s3_backend
  local_backend --> base_backend
  s3_backend --> base_backend
  parsers --> base_parser
  parsers --> edevis_parser
  parsers --> hdf5_parser
  parsers --> simulation_parser
  edevis_parser --> base_parser
  hdf5_parser --> base_parser
  simulation_parser --> base_parser
