classDiagram
  class pythermondt {
  }
  style pythermondt fill:#F2994A
  class __pkginfo__ {
  }
  style __pkginfo__ fill:#F2994A
  class config {
  }
  style config fill:#F2994A
  class data {
  }
  style data fill:#EB5757
  class dataset {
  }
  style dataset fill:#27AE60
  class io {
  }
  style io fill:#E0E0E0
  class readers {
  }
  style readers fill:#BB6BD9
  class transforms {
  }
  style transforms fill:#2F80ED
  class writers {
  }
  style writers fill:#F2994A
  pythermondt --> __pkginfo__
  pythermondt --> config
  pythermondt --> data
  pythermondt --> dataset
  pythermondt --> io
  pythermondt --> readers
  pythermondt --> transforms
  pythermondt --> writers
