classDiagram
  class pythermondt {
  }
  style pythermondt fill:#77AADD
  class __pkginfo__ {
  }
  style __pkginfo__ fill:#77AADD
  class config {
  }
  style config fill:#77AADD
  class data {
  }
  style data fill:#99DDFF
  class dataset {
  }
  style dataset fill:#44BB99
  class io {
  }
  style io fill:#BBCC33
  class readers {
  }
  style readers fill:#AAAA00
  class transforms {
  }
  style transforms fill:#EEDD88
  class writers {
  }
  style writers fill:#EE8866
  pythermondt --> __pkginfo__
  pythermondt --> config
  pythermondt --> data
  pythermondt --> dataset
  pythermondt --> io
  pythermondt --> readers
  pythermondt --> transforms
  pythermondt --> writers
