classDiagram
  class units {
  }
  style units fill:#77AADD
  class _unit {
  }
  style _unit fill:#77AADD
  class units {
  }
  style units fill:#77AADD
  class utils {
  }
  style utils fill:#77AADD
  units --> units
  units --> _unit
  units --> utils
  units --> _unit
  utils --> _unit
  utils --> units
