name: Trigger Run Tests

on:
  workflow_dispatch:

jobs:
  trigger-test:
    name: Trigger Test Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Call Reusable Workflow
        uses: ./.github/workflows/run_tests.yml@main