{% set name = "pythermondt" %}
{% set version = "0.2.1dev" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  # Even though we're using pip here, it's just to install the directory contents directly without a setup.py.
  # The actual build and dependencies are handled by conda-build and conda due to --no-deps flag.
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    # Build environment dependencies
    - python >=3.10, <3.13
    - pip
    - setuptools>=66.0
    - wheel>=0.4
  run:
    # General
    - tqdm>=4.65
    - ipywidgets>=8.0
    - ipykernel>=6.25
    - python>=3.10, <3.13

    # Data loading and visualization
    - h5py>=3.9
    - pymatreader>=1.0
    - numpy>=1.23
    - matplotlib>=3.7

    # Machine Learning
    - pytorch::pytorch>=2.0

    # AWS upload
    - boto3>=1.33

about:
  home: "https://github.com/voidsy-gmbh/pyThermoNDT"
  license: "Apache-2.0"
  license_file: "LICENSE"
  license_family: "APACHE"
  license_url: "https://github.com/voidsy-gmbh/pyThermoNDT/blob/main/LICENSE"
  summary: "A Python package for manipulating thermographic data in Non-Destructive Testing (NDT) applications."
  description: "pyThermoNDT is a Python package for manipulating thermographic data in Non-Destructive Testing (NDT) applications. It provides various methods to load, transform, visualize, and write thermographic data, making it easier and more efficient to work with thermal imaging in NDT contexts."

extra:
  recipe-maintainers:
    - julian.grimm@fh-wels.at
