package:
  name: pythermondt
  version: 0.0.1

source:
  path: ..

build:
  noarch: python
  number: 4
  # Even though we're using pip here, it's just to install the directory contents directly without a setup.py. 
  # The actual build and dependencies are handled by conda-build and conda due to --no-deps flag.
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.10
    - pip
  run:
    # General
    - python>=3.10
    - tqdm>=4.66.*
    - ipywidgets>=8.0.*

    # Data loading and visualization
    - h5py>=3.9, <3.11 # h5py 3.11.0 requires numpy 2.0.0 ==> not tested if this works here
    - mat73>=0.65
    - numpy>=1.23.*
    - matplotlib>=3.7.*

    # Machine Learning
    - pytorch::pytorch=2.3.*

    # AWS upload
    - boto3>=1.33.*

test:
  requires:
    - conda-forge::pytest=8.3.*
  source_files:
    - "./src/pythermondt/*"
    - "./tests/*.py"
  imports:
    - pythermondt
    - pythermondt.data
  commands:
    - pytest

about:
  home: "https://github.com/voidsy-gmbh/pyThermoNDT"
  license: "TBD"
  license_file: "LICENSE"
  summary: "A package to manipulate thermographic data for NDT purposes."
  description: "This package provides various methods to load, transform, visualize and write thermographic data. It serves as a tool to make working with thermographic data easier and more efficient."

extra:
  recipe-maintainers:
    - julian.grimm@fh-wels.at
